name: Docker CI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  docker-ci:
    uses: OmnisGenomics/.github/.github/workflows/docker-ci.yml@main
    with:
      build_args: >-
        --build-arg VERIBIOTA_VERSION=${{ github.ref_name }}
        --build-arg VERIBIOTA_BUILD_ID=${{ github.sha }}
      image_name: ghcr.io/omnisgenomics/veribiota:${{ github.ref_name }}
      image_tags: |
        ghcr.io/omnisgenomics/veribiota:latest
      labels: |
        org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        org.opencontainers.image.revision=${{ github.sha }}
      push: true
