name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    uses: OmnisGenomics/.github/.github/workflows/pages.yml@main
    with:
      package_attr: docs
    secrets: inherit
